services:
  mongo:
    image: mongodb/mongodb-community-server
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    depends_on:
      - mongo

  storage:
    image: redis
    volumes:
      - ./data:/data

  books:
    image: node:15.6
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - PORT=3000
      - SECONDAPP_URL=http://secondapp:4000
    ports:
      - 3000:3000
    command: npm run dev
    depends_on:
      - storage
      - mongo

  secondapp:
    image: node:15.6
    volumes:
      - ./secondapp:/app
    working_dir: /app
    environment:
      - PORT=4000
      - REDIS_URL=redis://storage
      - MONGO_URL=mongodb://mongo:27017
      - MONGODB_NAME=booksstor
    ports:
      - 4000:4000
    command: npm run dev
    depends_on:
      - storage
      - mongo
